server:
  port: 8081

spring:
  application:
    name: beacon-service

storage:
  type: local
  local:
    upload-dir: uploads
    public-path: /api/beacons/uploads

logging:
  level:
    com.lightsoundsanctuary.beacon_service: DEBUG