server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: useradmin
    password: userpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

jwt:
  secret: lightsoundsanctuary-super-secret-key-must-be-32-chars-min